// auth.js - Google Authenticator (TOTP) shared login for InvoiceFlow
//
// Design notes:
// - Uses Google Authenticator (TOTP) instead of a traditional password.
// - Sessions are stateless signed tokens (HMAC-SHA256), not stored server-side.
//
// Required env vars:
//   INVOICEFLOW_TOTP_SECRET  the secret key generated by the setup script
//   SESSION_SECRET           a long random string for cookie signing

const crypto = require('crypto');
const { authenticator } = require('otplib');

const TOTP_SECRET = process.env.INVOICEFLOW_TOTP_SECRET;
const SESSION_DURATION_MS = 7 * 24 * 60 * 60 * 1000; // 7 days
const COOKIE_NAME = 'invoiceflow_session';

if (!TOTP_SECRET) {
  console.warn('[auth] WARNING: INVOICEFLOW_TOTP_SECRET is not set! All logins will be rejected. Run the 2FA setup script.');
}

const secret = process.env.SESSION_SECRET || crypto.randomBytes(32).toString('hex');
if (!process.env.SESSION_SECRET) {
  console.warn('[auth] WARNING: SESSION_SECRET is not set - sessions will be invalidated on every restart. Set it in your environment.');
}

function sign(data) {
  return crypto.createHmac('sha256', secret).update(data).digest('hex');
}

function timingSafeStringEqual(a, b) {
  const bufA = Buffer.from(a);
  const bufB = Buffer.from(b);
  if (bufA.length !== bufB.length) return false;
  return crypto.timingSafeEqual(bufA, bufB);
}

// ---- Session tokens (stateless) ----

function createSessionToken() {
  const expires = Date.now() + SESSION_DURATION_MS;
  const payload = Buffer.from(JSON.stringify({ exp: expires })).toString('base64url');
  const signature = sign(payload);
  return { token: `${payload}.${signature}`, expires };
}

function isValidToken(token) {
  if (!token || !token.includes('.')) return false;
  const [payload, signature] = token.split('.');
  const expectedSignature = sign(payload);
  if (!timingSafeStringEqual(signature, expectedSignature)) return false;
  try {
    const data = JSON.parse(Buffer.from(payload, 'base64url').toString());
    return typeof data.exp === 'number' && Date.now() < data.exp;
  } catch {
    return false;
  }
}

// ---- Cookie helpers ----

function parseCookies(req) {
  const header = req.headers.cookie;
  const cookies = {};
  if (!header) return cookies;
  header.split(';').forEach(pair => {
    const idx = pair.indexOf('=');
    if (idx === -1) return;
    const key = pair.slice(0, idx).trim();
    const value = pair.slice(idx + 1).trim();
    cookies[key] = decodeURIComponent(value);
  });
  return cookies;
}

function setSessionCookie(res, token, expires) {
  const expiresStr = new Date(expires).toUTCString();
  const secureFlag = process.env.NODE_ENV === 'production' ? 'Secure; ' : '';
  res.setHeader('Set-Cookie',
    `${COOKIE_NAME}=${token}; HttpOnly; ${secureFlag}SameSite=Lax; Path=/; Expires=${expiresStr}`
  );
}

function clearSessionCookie(res) {
  res.setHeader('Set-Cookie',
    `${COOKIE_NAME}=; HttpOnly; SameSite=Lax; Path=/; Expires=Thu, 01 Jan 1970 00:00:00 GMT`
  );
}

function isAuthenticated(req) {
  const cookies = parseCookies(req);
  return isValidToken(cookies[COOKIE_NAME]);
}

// ---- TOTP check ----

function checkTotp(token) {
  if (!TOTP_SECRET) return false;
  if (!token || typeof token !== 'string') return false;
  try {
    return authenticator.check(token.trim(), TOTP_SECRET);
  } catch (e) {
    return false;
  }
}

// ---- Basic brute-force throttling (in-memory, per-IP) ----

const attempts = new Map(); // ip -> { count, resetAt }
const MAX_ATTEMPTS = 5;
const WINDOW_MS = 15 * 60 * 1000; // 15 minutes

function isRateLimited(ip) {
  const record = attempts.get(ip);
  if (!record) return false;
  if (Date.now() > record.resetAt) {
    attempts.delete(ip);
    return false;
  }
  return record.count >= MAX_ATTEMPTS;
}

function recordFailedAttempt(ip) {
  const record = attempts.get(ip);
  if (!record || Date.now() > record.resetAt) {
    attempts.set(ip, { count: 1, resetAt: Date.now() + WINDOW_MS });
  } else {
    record.count += 1;
  }
}

function clearAttempts(ip) {
  attempts.delete(ip);
}

setInterval(() => {
  const now = Date.now();
  for (const [ip, record] of attempts.entries()) {
    if (now > record.resetAt) attempts.delete(ip);
  }
}, 60 * 60 * 1000).unref();

module.exports = {
  COOKIE_NAME,
  createSessionToken,
  isValidToken,
  parseCookies,
  setSessionCookie,
  clearSessionCookie,
  isAuthenticated,
  checkTotp,
  isRateLimited,
  recordFailedAttempt,
  clearAttempts,
};
